package endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-30T17:40:54.615+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndPointTaskService",
                  wsdlLocation = "http://localhost:8080/task?wsdl",
                  targetNamespace = "http://endpoint/")
public class EndPointTaskService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint/", "EndPointTaskService");
    public final static QName EndPointTaskPort = new QName("http://endpoint/", "EndPointTaskPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/task?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndPointTaskService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/task?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndPointTaskService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndPointTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndPointTaskService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndPointTaskService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndPointTaskService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndPointTaskService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndPointTask
     */
    @WebEndpoint(name = "EndPointTaskPort")
    public EndPointTask getEndPointTaskPort() {
        return super.getPort(EndPointTaskPort, EndPointTask.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndPointTask
     */
    @WebEndpoint(name = "EndPointTaskPort")
    public EndPointTask getEndPointTaskPort(WebServiceFeature... features) {
        return super.getPort(EndPointTaskPort, EndPointTask.class, features);
    }

}
