package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-30T18:08:44.254+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndPointProject")
@XmlSeeAlso({ObjectFactory.class})
public interface EndPointProject {

    @WebMethod
    @Action(input = "http://endpoint/EndPointProject/deleteRequest", output = "http://endpoint/EndPointProject/deleteResponse")
    @RequestWrapper(localName = "delete", targetNamespace = "http://endpoint/", className = "endpoint.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://endpoint/", className = "endpoint.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointProject/findAllRequest", output = "http://endpoint/EndPointProject/findAllResponse")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://endpoint/", className = "endpoint.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.User> findAll();

    @WebMethod
    @Action(input = "http://endpoint/EndPointProject/createRequest", output = "http://endpoint/EndPointProject/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint/", className = "endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint/", className = "endpoint.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointProject/projectListRequest", output = "http://endpoint/EndPointProject/projectListResponse")
    @RequestWrapper(localName = "projectList", targetNamespace = "http://endpoint/", className = "endpoint.ProjectList")
    @ResponseWrapper(localName = "projectListResponse", targetNamespace = "http://endpoint/", className = "endpoint.ProjectListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.Project> projectList();

    @WebMethod
    @Action(input = "http://endpoint/EndPointProject/runRequest", output = "http://endpoint/EndPointProject/runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://endpoint/", className = "endpoint.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://endpoint/", className = "endpoint.RunResponse")
    public void run();
}
