package endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-19T10:50:18.729+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointUserService",
                  wsdlLocation = "http://localhost:8080/user?wsdl",
                  targetNamespace = "http://endpoint/")
public class EndpointUserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint/", "EndpointUserService");
    public final static QName EndpointUserPort = new QName("http://endpoint/", "EndpointUserPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/user?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointUserService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/user?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointUserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointUserService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointUserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointUserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointUserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointUser
     */
    @WebEndpoint(name = "EndpointUserPort")
    public EndpointUser getEndpointUserPort() {
        return super.getPort(EndpointUserPort, EndpointUser.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointUser
     */
    @WebEndpoint(name = "EndpointUserPort")
    public EndpointUser getEndpointUserPort(WebServiceFeature... features) {
        return super.getPort(EndpointUserPort, EndpointUser.class, features);
    }

}
