package endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-30T17:40:54.311+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndPointUserService",
                  wsdlLocation = "http://localhost:8080/user?wsdl",
                  targetNamespace = "http://endpoint/")
public class EndPointUserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint/", "EndPointUserService");
    public final static QName EndPointUserPort = new QName("http://endpoint/", "EndPointUserPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/user?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndPointUserService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/user?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndPointUserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndPointUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndPointUserService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndPointUserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndPointUserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndPointUserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndPointUser
     */
    @WebEndpoint(name = "EndPointUserPort")
    public EndPointUser getEndPointUserPort() {
        return super.getPort(EndPointUserPort, EndPointUser.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndPointUser
     */
    @WebEndpoint(name = "EndPointUserPort")
    public EndPointUser getEndPointUserPort(WebServiceFeature... features) {
        return super.getPort(EndPointUserPort, EndPointUser.class, features);
    }

}
