package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-31T11:39:40.371+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndPointSession")
@XmlSeeAlso({ObjectFactory.class})
public interface EndPointSession {

    @WebMethod
    @Action(input = "http://endpoint/EndPointSession/deleteSessionRequest", output = "http://endpoint/EndPointSession/deleteSessionResponse")
    @RequestWrapper(localName = "deleteSession", targetNamespace = "http://endpoint/", className = "endpoint.DeleteSession")
    @ResponseWrapper(localName = "deleteSessionResponse", targetNamespace = "http://endpoint/", className = "endpoint.DeleteSessionResponse")
    public void deleteSession(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointSession/addSessionRequest", output = "http://endpoint/EndPointSession/addSessionResponse")
    @RequestWrapper(localName = "addSession", targetNamespace = "http://endpoint/", className = "endpoint.AddSession")
    @ResponseWrapper(localName = "addSessionResponse", targetNamespace = "http://endpoint/", className = "endpoint.AddSessionResponse")
    public void addSession(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointSession/runRequest", output = "http://endpoint/EndPointSession/runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://endpoint/", className = "endpoint.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://endpoint/", className = "endpoint.RunResponse")
    public void run();
}
