package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-30T17:40:54.606+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndPointTask")
@XmlSeeAlso({ObjectFactory.class})
public interface EndPointTask {

    @WebMethod
    @Action(input = "http://endpoint/EndPointTask/deleteRequest", output = "http://endpoint/EndPointTask/deleteResponse")
    @RequestWrapper(localName = "delete", targetNamespace = "http://endpoint/", className = "endpoint.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://endpoint/", className = "endpoint.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointTask/findAllRequest", output = "http://endpoint/EndPointTask/findAllResponse")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://endpoint/", className = "endpoint.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.User> findAll();

    @WebMethod
    @Action(input = "http://endpoint/EndPointTask/createRequest", output = "http://endpoint/EndPointTask/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint/", className = "endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint/", className = "endpoint.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointTask/runRequest", output = "http://endpoint/EndPointTask/runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://endpoint/", className = "endpoint.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://endpoint/", className = "endpoint.RunResponse")
    public void run();
}
