package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T18:02:27.384+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndpointUser")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointUser {

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/authUserRequest", output = "http://endpoint/EndpointUser/authUserResponse")
    @RequestWrapper(localName = "authUser", targetNamespace = "http://endpoint/", className = "endpoint.AuthUser")
    @ResponseWrapper(localName = "authUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.AuthUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean authUser();

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/getUserListRequest", output = "http://endpoint/EndpointUser/getUserListResponse")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://endpoint/", className = "endpoint.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetUserListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.User> getUserList();

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/logOutUserRequest", output = "http://endpoint/EndpointUser/logOutUserResponse")
    @RequestWrapper(localName = "logOutUser", targetNamespace = "http://endpoint/", className = "endpoint.LogOutUser")
    @ResponseWrapper(localName = "logOutUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.LogOutUserResponse")
    public void logOutUser();

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/createUserRequest", output = "http://endpoint/EndpointUser/createUserResponse")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint/", className = "endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.CreateUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/findAllUserRequest", output = "http://endpoint/EndpointUser/findAllUserResponse")
    @RequestWrapper(localName = "findAllUser", targetNamespace = "http://endpoint/", className = "endpoint.FindAllUser")
    @ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindAllUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.User> findAllUser();

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/setCurrentUserRequest", output = "http://endpoint/EndpointUser/setCurrentUserResponse")
    @RequestWrapper(localName = "setCurrentUser", targetNamespace = "http://endpoint/", className = "endpoint.SetCurrentUser")
    @ResponseWrapper(localName = "setCurrentUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.SetCurrentUserResponse")
    public void setCurrentUser(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/getUserByIdRequest", output = "http://endpoint/EndpointUser/getUserByIdResponse")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://endpoint/", className = "endpoint.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public endpoint.User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndpointUser/getCurrentUserRequest", output = "http://endpoint/EndpointUser/getCurrentUserResponse")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://endpoint/", className = "endpoint.GetCurrentUser")
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetCurrentUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public endpoint.Session getCurrentUser();
}
