package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-31T17:41:05.278+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndpointDataBase")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointDataBase {

    @WebMethod
    @Action(input = "http://endpoint/EndpointDataBase/loadRequest", output = "http://endpoint/EndpointDataBase/loadResponse")
    @RequestWrapper(localName = "load", targetNamespace = "http://endpoint/", className = "endpoint.Load")
    @ResponseWrapper(localName = "loadResponse", targetNamespace = "http://endpoint/", className = "endpoint.LoadResponse")
    public void load();

    @WebMethod
    @Action(input = "http://endpoint/EndpointDataBase/saveRequest", output = "http://endpoint/EndpointDataBase/saveResponse")
    @RequestWrapper(localName = "save", targetNamespace = "http://endpoint/", className = "endpoint.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://endpoint/", className = "endpoint.SaveResponse")
    public void save();
}
