package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T18:02:27.764+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndpointSession")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointSession {

    @WebMethod
    @Action(input = "http://endpoint/EndpointSession/getSessionByUserIdRequest", output = "http://endpoint/EndpointSession/getSessionByUserIdResponse")
    @RequestWrapper(localName = "getSessionByUserId", targetNamespace = "http://endpoint/", className = "endpoint.GetSessionByUserId")
    @ResponseWrapper(localName = "getSessionByUserIdResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetSessionByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public endpoint.Session getSessionByUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndpointSession/addSessionRequest", output = "http://endpoint/EndpointSession/addSessionResponse")
    @RequestWrapper(localName = "addSession", targetNamespace = "http://endpoint/", className = "endpoint.AddSession")
    @ResponseWrapper(localName = "addSessionResponse", targetNamespace = "http://endpoint/", className = "endpoint.AddSessionResponse")
    public void addSession(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndpointSession/getNewSessionRequest", output = "http://endpoint/EndpointSession/getNewSessionResponse")
    @RequestWrapper(localName = "getNewSession", targetNamespace = "http://endpoint/", className = "endpoint.GetNewSession")
    @ResponseWrapper(localName = "getNewSessionResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetNewSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public endpoint.Session getNewSession(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndpointSession/deleteSessionRequest", output = "http://endpoint/EndpointSession/deleteSessionResponse")
    @RequestWrapper(localName = "deleteSession", targetNamespace = "http://endpoint/", className = "endpoint.DeleteSession")
    @ResponseWrapper(localName = "deleteSessionResponse", targetNamespace = "http://endpoint/", className = "endpoint.DeleteSessionResponse")
    public void deleteSession(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.Session arg0
    );
}
