package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-30T17:40:54.275+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndPointUser")
@XmlSeeAlso({ObjectFactory.class})
public interface EndPointUser {

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/logOutRequest", output = "http://endpoint/EndPointUser/logOutResponse")
    @RequestWrapper(localName = "logOut", targetNamespace = "http://endpoint/", className = "endpoint.LogOut")
    @ResponseWrapper(localName = "logOutResponse", targetNamespace = "http://endpoint/", className = "endpoint.LogOutResponse")
    public void logOut();

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/findAllRequest", output = "http://endpoint/EndPointUser/findAllResponse")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://endpoint/", className = "endpoint.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.User> findAll();

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/createRequest", output = "http://endpoint/EndPointUser/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint/", className = "endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint/", className = "endpoint.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/runRequest", output = "http://endpoint/EndPointUser/runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://endpoint/", className = "endpoint.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://endpoint/", className = "endpoint.RunResponse")
    public void run();

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/authRequest", output = "http://endpoint/EndPointUser/authResponse")
    @RequestWrapper(localName = "auth", targetNamespace = "http://endpoint/", className = "endpoint.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://endpoint/", className = "endpoint.AuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean auth();

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/setCurrentUserRequest", output = "http://endpoint/EndPointUser/setCurrentUserResponse")
    @RequestWrapper(localName = "setCurrentUser", targetNamespace = "http://endpoint/", className = "endpoint.SetCurrentUser")
    @ResponseWrapper(localName = "setCurrentUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.SetCurrentUserResponse")
    public void setCurrentUser(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/EndPointUser/getCurrentUserRequest", output = "http://endpoint/EndPointUser/getCurrentUserResponse")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://endpoint/", className = "endpoint.GetCurrentUser")
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetCurrentUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public endpoint.User getCurrentUser();
}
