package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-15T13:23:20.957+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "EndpointTask")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointTask {

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/deleteTaskRequest", output = "http://endpoint/EndpointTask/deleteTaskResponse", fault = {@FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint/EndpointTask/deleteTask/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://endpoint/", className = "endpoint.DeleteTask")
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://endpoint/", className = "endpoint.DeleteTaskResponse")
    public void deleteTask(
        @WebParam(name = "session", targetNamespace = "")
        endpoint.Session session,
        @WebParam(name = "idTask", targetNamespace = "")
        java.lang.String idTask
    ) throws AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/createTaskRequest", output = "http://endpoint/EndpointTask/createTaskResponse", fault = {@FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint/EndpointTask/createTask/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint/", className = "endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint/", className = "endpoint.CreateTaskResponse")
    public void createTask(
        @WebParam(name = "session", targetNamespace = "")
        endpoint.Session session,
        @WebParam(name = "task", targetNamespace = "")
        endpoint.Task task
    ) throws AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/checkTaskListIsEmptyRequest", output = "http://endpoint/EndpointTask/checkTaskListIsEmptyResponse")
    @RequestWrapper(localName = "checkTaskListIsEmpty", targetNamespace = "http://endpoint/", className = "endpoint.CheckTaskListIsEmpty")
    @ResponseWrapper(localName = "checkTaskListIsEmptyResponse", targetNamespace = "http://endpoint/", className = "endpoint.CheckTaskListIsEmptyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean checkTaskListIsEmpty();

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/openTaskByNameRequest", output = "http://endpoint/EndpointTask/openTaskByNameResponse", fault = {@FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint/EndpointTask/openTaskByName/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "openTaskByName", targetNamespace = "http://endpoint/", className = "endpoint.OpenTaskByName")
    @ResponseWrapper(localName = "openTaskByNameResponse", targetNamespace = "http://endpoint/", className = "endpoint.OpenTaskByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.Task> openTaskByName(
        @WebParam(name = "session", targetNamespace = "")
        endpoint.Session session,
        @WebParam(name = "nameTask", targetNamespace = "")
        java.lang.String nameTask
    ) throws AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/findAllTaskRequest", output = "http://endpoint/EndpointTask/findAllTaskResponse", fault = {@FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint/EndpointTask/findAllTask/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "findAllTask", targetNamespace = "http://endpoint/", className = "endpoint.FindAllTask")
    @ResponseWrapper(localName = "findAllTaskResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindAllTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.Task> findAllTask(
        @WebParam(name = "session", targetNamespace = "")
        endpoint.Session session
    ) throws AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/deleteTaskByIdProjecrRequest", output = "http://endpoint/EndpointTask/deleteTaskByIdProjecrResponse", fault = {@FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint/EndpointTask/deleteTaskByIdProjecr/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "deleteTaskByIdProjecr", targetNamespace = "http://endpoint/", className = "endpoint.DeleteTaskByIdProjecr")
    @ResponseWrapper(localName = "deleteTaskByIdProjecrResponse", targetNamespace = "http://endpoint/", className = "endpoint.DeleteTaskByIdProjecrResponse")
    public void deleteTaskByIdProjecr(
        @WebParam(name = "session", targetNamespace = "")
        endpoint.Session session,
        @WebParam(name = "idProject", targetNamespace = "")
        java.lang.String idProject
    ) throws AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint/EndpointTask/getTaskByProjectNameRequest", output = "http://endpoint/EndpointTask/getTaskByProjectNameResponse", fault = {@FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint/EndpointTask/getTaskByProjectName/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "getTaskByProjectName", targetNamespace = "http://endpoint/", className = "endpoint.GetTaskByProjectName")
    @ResponseWrapper(localName = "getTaskByProjectNameResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetTaskByProjectNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.Task> getTaskByProjectName(
        @WebParam(name = "session", targetNamespace = "")
        endpoint.Session session,
        @WebParam(name = "projectName", targetNamespace = "")
        java.lang.String projectName
    ) throws AccessForbiddenException_Exception;
}
