package endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-31T12:46:15.530+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint/", name = "UserEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndPoint {

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/authUserRequest", output = "http://endpoint/UserEndPoint/authUserResponse")
    @RequestWrapper(localName = "authUser", targetNamespace = "http://endpoint/", className = "endpoint.AuthUser")
    @ResponseWrapper(localName = "authUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.AuthUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean authUser();

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/runRequest", output = "http://endpoint/UserEndPoint/runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://endpoint/", className = "endpoint.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://endpoint/", className = "endpoint.RunResponse")
    public void run();

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/createUserRequest", output = "http://endpoint/UserEndPoint/createUserResponse")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint/", className = "endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.CreateUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/logOutUserRequest", output = "http://endpoint/UserEndPoint/logOutUserResponse")
    @RequestWrapper(localName = "logOutUser", targetNamespace = "http://endpoint/", className = "endpoint.LogOutUser")
    @ResponseWrapper(localName = "logOutUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.LogOutUserResponse")
    public void logOutUser();

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/findAllUserRequest", output = "http://endpoint/UserEndPoint/findAllUserResponse")
    @RequestWrapper(localName = "findAllUser", targetNamespace = "http://endpoint/", className = "endpoint.FindAllUser")
    @ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindAllUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<endpoint.User> findAllUser();

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/setCurrentUserRequest", output = "http://endpoint/UserEndPoint/setCurrentUserResponse")
    @RequestWrapper(localName = "setCurrentUser", targetNamespace = "http://endpoint/", className = "endpoint.SetCurrentUser")
    @ResponseWrapper(localName = "setCurrentUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.SetCurrentUserResponse")
    public void setCurrentUser(
        @WebParam(name = "arg0", targetNamespace = "")
        endpoint.User arg0
    );

    @WebMethod
    @Action(input = "http://endpoint/UserEndPoint/getCurrentUserRequest", output = "http://endpoint/UserEndPoint/getCurrentUserResponse")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://endpoint/", className = "endpoint.GetCurrentUser")
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetCurrentUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public endpoint.User getCurrentUser();
}
